title: Stephen's Blog
description: "Blog about networking, security and pharmacy"
author:
  name: "Stephen"
#  email: "someone@somewebsite.somedomain"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Stephen"
year : "2020"
